[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install --legacy-peer-deps", "npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && node src/server.js"
